# Generated by Django 6.0.2 on 2026-03-05 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_budget', models.IntegerField(blank=True, help_text='Maximum monthly budget', null=True)),
                ('preferred_food', models.CharField(choices=[('any', 'Any'), ('veg', 'Pure Veg'), ('jain', 'Jain Food Only')], default='any', max_length=10)),
                ('requires_ac', models.BooleanField(default=False)),
                ('requires_wifi', models.BooleanField(default=False)),
                ('requires_bathroom', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
