# Generated by Django 6.0.2 on 2026-02-24 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('single_meal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_veg_only', models.BooleanField(default=False)),
                ('has_jain_food', models.BooleanField(default=False)),
                ('has_non_veg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='messes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.mess')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('breakfast_items', models.TextField(blank=True, help_text='List items separated by commas')),
                ('lunch_items', models.TextField(blank=True, help_text='List items separated by commas')),
                ('dinner_items', models.TextField(blank=True, help_text='List items separated by commas')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='food.mess')),
            ],
            options={
                'unique_together': {('mess', 'date')},
            },
        ),
    ]
