# Generated by Django 6.0.2 on 2026-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='breakfast_items',
            field=models.TextField(blank=True, help_text='List items on separate lines'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='dinner_items',
            field=models.TextField(blank=True, help_text='List items on separate lines'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='lunch_items',
            field=models.TextField(blank=True, help_text='List items on separate lines'),
        ),
    ]
