# Generated by Django 6.0.2 on 2026-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_dailymenu_breakfast_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mess_images/'),
        ),
    ]
