# Generated by Django 6.0.2 on 2026-03-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_mess_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mess',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
