# Generated by Django 6.0.2 on 2026-03-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_mess_latitude_mess_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessReview',
        ),
    ]
