# Generated by Django 6.0.2 on 2026-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_delete_messreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='has_jain_food',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mess',
            name='has_non_veg',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mess',
            name='is_veg_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mess',
            name='monthly_fee',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8),
        ),
    ]
