# Generated by Django 6.0.2 on 2026-04-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_mess_has_jain_food_alter_mess_has_non_veg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='food.mess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mess', 'user')},
            },
        ),
    ]
