# Generated by Django 6.0.2 on 2026-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_remove_room_is_available_room_vacant_beds_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pg_images/'),
        ),
    ]
