# Generated by Django 6.0.2 on 2026-03-05 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_pg_latitude_pg_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('pg', 'PG'), ('mess', 'Mess')], max_length=4)),
                ('listing_id', models.IntegerField()),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['listing_type', 'listing_id', 'viewed_at'], name='housing_lis_listing_0cfad1_idx')],
            },
        ),
    ]
