# Generated by Django 6.0.2 on 2026-03-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_listingview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGReview',
        ),
    ]
