# Generated by Django 6.0.2 on 2026-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_delete_pgreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='food_included',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pg',
            name='gender_restriction',
            field=models.CharField(choices=[('boys', 'Boys only'), ('girls', 'Girls only'), ('any', 'Anyone')], db_index=True, default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='pg',
            name='starting_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8),
        ),
    ]
