# Generated by Django 6.0.2 on 2026-04-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_alter_pg_food_included_alter_pg_gender_restriction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='housing.pg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pg', 'user')},
            },
        ),
    ]
